#pragma config(Motor,  port2,           1,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           2,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           3,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           4,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftTopTower,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightTopTower, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftBottomTower, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightBottomTower, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){
		//chassis drive
		motor[1] = vexRT[Ch3];
		motor[2] = vexRT[Ch3];
		motor[3] = vexRT[Ch2];
		motor[4] = vexRT[Ch2];
		/*
		Current chassis drive spins in circles
		must difine left vs. right for each motor to fix
		*/
		//tower arc drive
		motor[leftTopTower] = vexRT[Ch2Xmtr2];
		motor[leftBottomTower] = vexRT[Ch2Xmtr2];
		motor[rightTopTower] = vexRT[Ch3Xmtr2];
		motor[rightBottomTower] = vexRT[Ch3Xmtr2];
	}//while
}//task main
