#pragma config(Motor,  port2,           1,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           2,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           3,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           4,             tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true){
	motor[1] = vexRT[Ch3];
	motor[2] = vexRT[Ch3];
	motor[3] = vexRT[Ch2];
	motor[4] = vexRT[Ch2];
	}


}
