#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rearRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rearLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor[frontLeft] = vexRT[Ch3];
		motor[rearLeft] = vexRT[Ch3];
		motor[frontRight] = vexRT[Ch2];
		motor[rearRight] = vexRT[Ch2];
	}


}
