#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightRear,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftRear,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftTopTower,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightTopTower, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftBottomTower, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightBottomTower, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){
		//chassis drive
		motor[rightFront] = vexRT[Ch2];
		motor[rightRear] = vexRT[Ch2];
		motor[leftFront] = vexRT[Ch3];
		motor[leftRear] = vexRT[Ch3];

		//tower arc drive
		motor[leftTopTower] = vexRT[Ch2Xmtr2];
		motor[leftBottomTower] = vexRT[Ch2Xmtr2];
		motor[rightTopTower] = vexRT[Ch3Xmtr2];
		motor[rightBottomTower] = vexRT[Ch3Xmtr2];
	}//while
}//task main
